// <auto-generated />
using HappyEnglishWebApi.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HappyEnglishWebApi.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221108121221_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("HappyEnglishWebApi.Model.Gamer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Gamer");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Age = 32,
                            FirstName = "Anton",
                            LastName = "Lukyantsev"
                        });
                });

            modelBuilder.Entity("HappyEnglishWebApi.Model.Word", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Word");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Value = "Anton"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
